-- ═══════════════════════════════════════════════════════════════════
-- Sillage Core Schema
-- ═══════════════════════════════════════════════════════════════════
-- Migration ID: 20260630_00001
-- Purpose:     Foundation tables for fragrance data from Parfumo CSV
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

-- ── Enums ──────────────────────────────────────────────────────────

CREATE TYPE import_source AS ENUM (
  'parfumo'
);

COMMENT ON TYPE import_source IS 'Data source identifier. Extended with ALTER TYPE when new sources are added.';

CREATE TYPE concentration AS ENUM (
  'EDT',
  'EDP',
  'Parfum',
  'Eau Fraiche',
  'Cologne',
  'Eau de Cologne',
  'Extrait',
  'Aftershave'
);

COMMENT ON TYPE concentration IS 'Normalized fragrance concentration levels. Mapped from source-specific terminology during import.';

CREATE TYPE note_position AS ENUM (
  'top',
  'heart',
  'base'
);

COMMENT ON TYPE note_position IS 'Pyramid position in a fragrance note breakdown.';

-- ── Brands ─────────────────────────────────────────────────────────

CREATE TABLE brands (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT        NOT NULL,
  name        TEXT        NOT NULL CHECK (trim(name) <> ''),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_brands_slug ON brands (slug);
CREATE UNIQUE INDEX idx_brands_name ON brands (name);

COMMENT ON TABLE  brands              IS 'Perfume houses and manufacturers. Canonical brand names referenced by all fragrances.';
COMMENT ON COLUMN brands.slug         IS 'URL-safe identifier. Generated by the import normalizer from the canonical name.';
COMMENT ON COLUMN brands.name         IS 'Canonical brand name (e.g. "Parfums de Marly"). Trimmed, title-cased, deduplicated via UNIQUE constraint.';

-- ── Perfumers ──────────────────────────────────────────────────────

CREATE TABLE perfumers (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT        NOT NULL,
  name        TEXT        NOT NULL CHECK (trim(name) <> ''),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_perfumers_slug ON perfumers (slug);
CREATE UNIQUE INDEX idx_perfumers_name ON perfumers (name);

COMMENT ON TABLE  perfumers              IS 'Individual perfumers (nose) who created fragrances. Many-to-many with fragrances.';
COMMENT ON COLUMN perfumers.slug         IS 'URL-safe identifier generated from the perfumer name.';
COMMENT ON COLUMN perfumers.name         IS 'Canonical perfumer name (e.g. "Olivier Creed"). Deduplicated via UNIQUE constraint.';

-- ── Fragrances ─────────────────────────────────────────────────────

CREATE TABLE fragrances (
  id                UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id          UUID            NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
  name              TEXT            NOT NULL CHECK (trim(name) <> ''),
  slug              TEXT            NOT NULL,
  type              TEXT,
  concentration     concentration,
  launch_year       SMALLINT        CHECK (launch_year IS NULL OR (launch_year >= 1800 AND launch_year <= 2100)),
  rating_average    NUMERIC(3, 2)   CHECK (rating_average IS NULL OR (rating_average >= 0 AND rating_average <= 10)),
  rating_count      INTEGER         CHECK (rating_count IS NULL OR rating_count >= 0),
  source            import_source   NOT NULL,
  external_id       TEXT,
  external_url      TEXT,
  import_hash       TEXT            NOT NULL,
  raw_data          JSONB,
  created_at        TIMESTAMPTZ     NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_fragrances_slug             ON fragrances (slug);
CREATE UNIQUE INDEX idx_fragrances_import_hash      ON fragrances (import_hash);
CREATE UNIQUE INDEX idx_fragrances_brand_name_type  ON fragrances (brand_id, name, COALESCE(type, ''));
CREATE INDEX       idx_fragrances_brand_id          ON fragrances (brand_id);

COMMENT ON TABLE  fragrances                   IS 'Core entity. One row = one fragrance variant (e.g. "Herod EDP" under Parfums de Marly).';
COMMENT ON COLUMN fragrances.slug              IS 'Globally unique URL-safe identifier. Generated by the import normalizer as slugify(brand_name || " " || fragrance_name). The importer is responsible for slug generation, not the database.';
COMMENT ON COLUMN fragrances.type              IS 'Free-text type descriptor from the source (e.g. "Extrait de Parfum"). May overlap with concentration. Kept as TEXT because source values may have uncontrolled variants.';
COMMENT ON COLUMN fragrances.concentration     IS 'Normalized concentration level. Mapped from source terminology during import.';
COMMENT ON COLUMN fragrances.launch_year       IS 'Year of release. NULL when unknown. Constrained to 1800-2100.';
COMMENT ON COLUMN fragrances.rating_average    IS 'Average user rating on Parfumo. Scale 0-10. Two decimal places.';
COMMENT ON COLUMN fragrances.rating_count      IS 'Number of user ratings submitted on Parfumo.';
COMMENT ON COLUMN fragrances.source            IS 'Identifies which data source this record originated from.';
COMMENT ON COLUMN fragrances.external_id       IS 'Original identifier in the source system (Parfumo slug or ID).';
COMMENT ON COLUMN fragrances.external_url      IS 'Canonical URL to the fragrance on the source website.';
COMMENT ON COLUMN fragrances.import_hash       IS 'SHA-256 hex digest for idempotent imports. Deterministic: SHA256(source || external_id || brand_name || fragrance_name). Unique constraint prevents duplicate rows.';
COMMENT ON COLUMN fragrances.raw_data          IS 'Original CSV row serialized as JSON. Used for debugging the import pipeline. Should be dropped before production launch.';

-- ── Accords ────────────────────────────────────────────────────────

CREATE TABLE accords (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT        NOT NULL,
  name        TEXT        NOT NULL CHECK (trim(name) <> ''),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_accords_slug ON accords (slug);
CREATE UNIQUE INDEX idx_accords_name ON accords (name);

COMMENT ON TABLE  accords              IS 'Controlled taxonomy of fragrance accords (e.g. "Woody", "Spicy", "Sweet"). Shared across many fragrances via the join table.';
COMMENT ON COLUMN accords.slug         IS 'URL-safe identifier from the accord name.';
COMMENT ON COLUMN accords.name         IS 'Canonical accord name. Deduplicated via UNIQUE constraint.';

-- ── Fragrance ↔ Accords (join) ─────────────────────────────────────

CREATE TABLE fragrance_accords (
  fragrance_id  UUID NOT NULL REFERENCES fragrances(id) ON DELETE CASCADE,
  accord_id     UUID NOT NULL REFERENCES accords(id) ON DELETE RESTRICT,
  intensity     TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (fragrance_id, accord_id)
);

CREATE INDEX idx_fragrance_accords_accord_id ON fragrance_accords (accord_id);

COMMENT ON TABLE  fragrance_accords                 IS 'Many-to-many join between fragrances and accords.';
COMMENT ON COLUMN fragrance_accords.intensity       IS 'Optional intensity qualifier from the source (e.g. "strong", "moderate", "subtle"). Kept as TEXT because values may vary across sources.';

-- ── Notes ──────────────────────────────────────────────────────────

CREATE TABLE notes (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT        NOT NULL,
  name        TEXT        NOT NULL CHECK (trim(name) <> ''),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_notes_slug ON notes (slug);
CREATE UNIQUE INDEX idx_notes_name ON notes (name);

COMMENT ON TABLE  notes              IS 'Controlled taxonomy of fragrance notes (e.g. "Bergamot", "Vanilla", "Leather"). Minimal table — no category classification.';
COMMENT ON COLUMN notes.slug         IS 'URL-safe identifier from the note name.';

-- ── Fragrance ↔ Notes (join) ───────────────────────────────────────

CREATE TABLE fragrance_notes (
  fragrance_id  UUID            NOT NULL REFERENCES fragrances(id) ON DELETE CASCADE,
  note_id       UUID            NOT NULL REFERENCES notes(id) ON DELETE RESTRICT,
  position      note_position   NOT NULL,
  intensity     TEXT,
  created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
  PRIMARY KEY (fragrance_id, note_id, position)
);

CREATE INDEX idx_fragrance_notes_note_id     ON fragrance_notes (note_id);
CREATE INDEX idx_fragrance_notes_fragrance   ON fragrance_notes (fragrance_id, position);

COMMENT ON TABLE  fragrance_notes                IS 'Many-to-many join between fragrances and notes with pyramid position (top/heart/base).';
COMMENT ON COLUMN fragrance_notes.position       IS 'Pyramid tier: top (head), heart (middle), or base. ENUM enforced at database level.';
COMMENT ON COLUMN fragrance_notes.intensity      IS 'Optional intensity qualifier from the source. Kept as TEXT for flexibility.';

-- ── Fragrance ↔ Perfumers (join) ───────────────────────────────────

CREATE TABLE fragrance_perfumers (
  fragrance_id  UUID NOT NULL REFERENCES fragrances(id) ON DELETE CASCADE,
  perfumer_id   UUID NOT NULL REFERENCES perfumers(id) ON DELETE RESTRICT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (fragrance_id, perfumer_id)
);

CREATE INDEX idx_fragrance_perfumers_perfumer_id ON fragrance_perfumers (perfumer_id);

COMMENT ON TABLE fragrance_perfumers IS 'Many-to-many join between fragrances and perfumers. A fragrance may have multiple perfumers (collaborations).';

COMMIT;